service: stocks
 
plugins:
  - serverless-python-requirements
  - serverless-offline
 
custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8

package:
  exclude:
    - node_modules/**
    - env/**

functions:
  get-stocks:
    handler: handler.run
    events:
      - http:
            method: GET
            path: /stock
            cors:
              origin: '*'
              headers:
                - Access-Control-Allow-Headers
                - Access-Control-Allow-Origin
                - Authorization
                - Content-Type
                - X-Amz-Date
                - X-Amz-Security-Token
                - X-Amz-User-Agent
                - X-Api-Key
